version: "3.7"

networks:
  cl-mojaloop-net:
    name: cl-mojaloop-net

services:
  tigerbeetle-setup:
    image: ghcr.io/tigerbeetledb/tigerbeetle:latest
    container_name: cl_tigerbeetle_setup
    command: "format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker/tigerbeetle:/data

  tigerbeetle:
    image: ghcr.io/tigerbeetledb/tigerbeetle:latest
    container_name: cl_tigerbeetle
    command: "start --addresses=0.0.0.0:5001 /data/0_0.tigerbeetle"
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker/tigerbeetle:/data
    networks:
      - cl-mojaloop-net
    ports:
      - 5001:5001
    depends_on:
      - tigerbeetle-setup
    healthcheck:
      test: ["CMD", "/tigerbeetle" ,"version"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  mockserver:
    image: jamesdbloom/mockserver
    container_name: mockserver
    deploy:
      replicas: 1
    ports:
      - "1080:1080"
    networks:
      - cl-mojaloop-net

  temp_curl:
    image: byrnedo/alpine-curl
    container_name: cl_temp_curl
    links:
      - mockserver
    volumes:
      - ./docker/wait-for:/opt/wait-for
    entrypoint: [ "sh", "-c" ]
    command:
      - /opt/wait-for/wait-for-mockserver.sh
    environment: []
    networks:
      - cl-mojaloop-net
    depends_on:
      - mockserver

  simulator:
    image: mojaloop/simulator:latest
    container_name: cl_simulator
    user: root
    deploy:
      replicas: 1
    ports:
      - "8444:8444"
    environment:
      - LOG_LEVEL=info
      - TRANSFERS_ENDPOINT=http://host.docker.internal:3000
      - QUOTES_ENDPOINT=http://host.docker.internal:3002
      - PARTIES_ENDPOINT=http://host.docker.internal:4002
      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
      - TRANSFERS_CONDITION=HOr22-H3AfTDHrSkPjJtVPRdKouuMkDXTR4ejlQa8Ks
      - TRANSFERS_FULFILMENT=XoSz1cL0tljJSCp_VtIYmPNw-zFUgGfbUqf69AagUzY
    networks:
      - cl-mojaloop-net
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:8444/health"]
      timeout: 20s
      retries: 10
      interval: 30s

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    container_name: cl_kowl
    deploy:
      replicas: 1
    restart: on-failure
    hostname: kowl
    ports:
    - "8080:8080"
    networks:
      - cl-mojaloop-net
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
