extends:
  - "../../.eslintrc.yaml"

rules: {} # Added to the ones specified on the parent file.

overrides:
  # On some implementation files, the type any is often necessary.
  - files:
      - "./src/implementations/builtin_ledger_adapter.ts"
      - "./src/implementations/chart_of_accounts_mongo_repo.ts"
    rules:
      "@typescript-eslint/no-explicit-any":
        - "off"